[DEFAULT]
## this section is just used as default for all the "s3 *"
## sections, you can place these variables also directly there

## replace with e.g. "localhost" to run against local software
host = localhost

## uncomment the port to use something other than 80
port = 8000

## say "no" to disable TLS
is_secure = no

## AWS access key
access_key = 0555b35654ad1656d804

## AWS secret key
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==

## all the buckets created will start with this prefix;
## {random} will be filled with random characters to pad
## the prefix to 30 characters long, and avoid collisions
bucket_prefix = YOURNAMEHERE-{random}-
